apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/LaurentMourer/argo-cd-example.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'templateName'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/LaurentMourer/argo-cd-example.git
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true